### ISSUE TITLE
Chave por e-mail é sensitive

### ISSUE THREAD

**Issue by neyestrabelli** [fbbergamo/gerador-pix#1]
Bacana seu projeto, porém precisa fazer um ajuste no caso de usar a chave por e-mail, ela é case sensitive e seu programa passa tudo para maiúsculas.

Obrigado :)

**Comment by fbbergamo** [comment]
Opa,vlw! vou verificar, fiquei confuso com as mudanças da documentação 

pq começei seguindo a doc 2.0.0 e passou p 2.0.1.

E pelo jeito retiraram essa parte, deve ser isso que tá dando erro no itau 

![doc-email](https://user-images.githubusercontent.com/1224193/99886590-7c3cd500-2c1c-11eb-87e3-c2aa66a9fab7.png)

**Comment by fbbergamo** [comment]
Ajustado, obrigado!

**Comment by renatofrota** [comment]
A documentação mais atual de padrões de iniciação Pix (válida para o Go Live 16/11) não tem esse requerimento. Pode ficar minúsculo e com @.

https://www.bcb.gov.br/estabilidadefinanceira/pix > Regulamentação relacionada ao Pix > Manual de Padrões para Iniciação do Pix.
