### ISSUE TITLE
Comprovante Pix

### ISSUE THREAD

**Issue by brunolhamasdesigner** [fbbergamo/gerador-pix#11]
Boa noite Felipe! Passando para dizer que o gerador de pix online é muito prático, tenho usado diariamente para meu projeto de placas de qr code pix. Gostaria de saber se tem como colocar um campo para inserir numero do whatsapp. Por exemplo quando eu ler o qrcode e pagar o pix enviar o comprovante de pagamento direto para esse numero do whats. Qualquer coisa me envie um e-mail que passo meu whats para conversar melhor.

**Comment by fbbergamo** [comment]
olá, pelo que eu entendo não tem como usando o QrCode estatico, pq não tem como o banco avisar um sistema que o pagamento foi feito. 

Dá para fazer algo com o QRCode dinamico, usando alguma API que tem integração com o sistema pix do Bacen. Ae ele consegue avisar o sistema que aquele QrCode foi pago, e vc pode enviar o comprovante para um numero de whatsapp, mas isso tem que ver com alguma empresa de pagamento e fazer a integração. 

Abraços.
