### ISSUE TITLE
Dúvida na Utilização do Código

### ISSUE THREAD

**Issue by ronaldofl** [fbbergamo/gerador-pix#2]
Tenho uma dúvida na utilização do código que é a seguinte, notei que é feito um post para a URL: /emvqr-static
Porém não encontrei esse diretório dentro do código fonte disponibilizado no GitHub.

Estou cometendo algum engano ou é preciso sempre fazer o post para o endereço externo: https://www.gerarpix.com.br/emvqr-static ?

Gostaria de realizar a geração de forma totalmente local no meu sistema. É possível?
Caso não seja possível com o fonte presente no Github, podemos negociar para que você crie uma implementação personalizada para o meu caso?

**Comment by sibelius** [comment]
https://github.com/fbbergamo/gerador-pix/blob/main/index.js#L53

**Comment by fbbergamo** [comment]
@ronaldofl  se você estiver fazendo em javascript pode usar essa lib para gerar o QrCode https://github.com/fbbergamo/gerador-pix/blob/main/lib/br_code.js, e olhar o link que o @sibelius  colocou 

Tá sem teste e não tá 100% isolado do site, mas se quiser poder forka o projeto ou copiar e colar no seu. 

Ou tb uma outra opção é subir essa aplicação em um servidor e usar esse endpoint como um serviço. 
Qualquer coisa só chamar aqui
Abraços
