### ISSUE TITLE
brecha no código, faltando informações

### ISSUE THREAD

**Issue by MTHS1901** [fbbergamo/gerador-pix#21]
notei que não é só alterar o nome da referencia, ela tambem gera alguns parametros antes e depois, porem nao consigo identificar esse padrão.

Exemplo, tenho 3 strings
${NOME_DA_CIDADE}62090505TESTE6304A7CB (Nesse caso a referencia é "TESTE")
${NOME_DA_CIDADE}6208050412346304022B (Nesse caso a referencia e "1234")
${NOME_DA_CIDADE}62130509DEVELOPER6304B68B  (Nesse caso a referencia é "DEVELOPER")

é notavel que alem da referencia, há uma mudança de parametros antes e depois de cada referencia, mas nao consigo entender e identificar este padrão.

eu seiq ue antes da referencia tem o contador de quantos caracteres tem a referencia, por ex: 
${NOME_DA_CIDADE}62130509DEVELOPER6304B68B o "09" antes de DEVELOPER refere que a referencia tem 9 caracteres, mas como eu poderia entender o restante dos padrões?

**Comment by ghost** [comment]
recomendo a leitura desses manuais para entender o restante dos padrões:
- manual do BrCode do BCB - https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf

- manual referente ao padrão do QR code que o BrCode segue - https://www.emvco.com/specifications/emv-qr-code-specification-for-payment-systems-emv-qrcps-merchant-presented-mode/

resumindo as informaçoes estão dispostas assim:
[CODIGO DO CAMPO] [TAMANHO DO VALOR DO CAMPO] [VALOR DO CAMPO]

sendo que os campos podem ser aninhados, dai o tamanho do campo que possui filhos tem seu tamanho calculado nos valor necessario para representar seu filho - incluindo o seu código e o valor que representa o tamanho do filho em especifico(2(codigo) + 2(numero de 01 a 99 normalmente).
