### ISSUE TITLE
Com valor informado, o código pix ficou inválido.

### ISSUE THREAD

**Issue by airtonluciano** [fbbergamo/gerador-pix#4]
Bom dia, Felipe! Parabéns pelo projeto e por disponibilizá-lo. Usei o site para gerar código pix de diversos lavadores de carros e profissionais que atuam na barbearia do Senado Federal. Por conta da pandemia e do fechamento do Congresso, eles ficaram sem renda e temos organizado campanhas de arrecadação para apoiá-los. O seu código facilitou muito. Obrigado!

Para os códigos deles, fiz a geração sem valores prévios, e funcionou perfeitamente. Hoje lançamos a ferramenta e fui testar um código para fazer o PIX de uma conta minha para outra, também minha. Dessa vez, informei um valor, 1000. Mas aí nem o Inter nem o Nubank aceitaram. Bastou eu retirar o valor e o código voltou a funcionar perfeitamente.

Abraços!

**Comment by airtonluciano** [comment]
Também percebi que da semana para cá, quando é informado um Texto de referência que contenha espaços ou pontos, o código gerado fica inválido. Semana passada eu gerei vários sem essa preocupação

**Comment by fbbergamo** [comment]
@airtonluciano obrigado pelo retorno, 

Corrigi a parte do valor com casa decimal de milhares.

O texto de referencia é o identificador da transferência pelo que eu vi ele só deve ser números e letras, coloquei a validação para deixar só letras e números, pelo q eu vi alguns bancos podem dar erro com espaço mesmo. 

No final de semana vou colocar o "detalhes da transferência" esse campo deve permitir espaços.

Abraços, e obrigado pelo retorno!

**Comment by airtonluciano** [comment]
Mais uma vez, parabéns pela solução e muito obrigado pela atenção. Caso não tenha percebido, há uma outra validação necessária, que afeta alguns bancos: retirar espaços à esquerda e à direita do nome do beneficiário. Eu cheguei a essas situações pois fiz cerca de 40 códigos, usando Copia e Cola para preencher os campos. Não é algo normal de acontecer quando se preenche manualmente cada um, de qualquer modo, fica a sugestão para deixar sua solução ainda melhor. Abraços!

**Comment by fbbergamo** [comment]
@airtonluciano corrigido!

Coloquei uma forma de imprimir a plaquinha pix tb. Abraços,
