### ISSUE TITLE
Pix chave para agência e conta bancária

### ISSUE THREAD

**Issue by FelipeZini** [fbbergamo/gerador-pix#5]
Como fazer a utilização para enviar um PIX sendo a chave a banco, agência e conta bancária?

**Comment by fbbergamo** [comment]
Olá, vc tem algum exemplo de um banco que tem isso? 

não vi nenhuma especificação no documento do Bacen, acredito que estão usando uma chave aleatória com os dados da conta.

**Comment by FelipeZini** [comment]
Não achei na documentação, mas no aplicativos dos bancos é possível realizar um PIX informando agência, conta e documento (cpf/cnpj);
Aí gostaria de saber se é possível gerar um QR Code com essas informações, tenho um sistema onde o pagamento tem que ser realizado numa conta específica (não dá para garantir que o documento seja a chave da conta que meu cliente quer receber).

Fazemos esse procedimento entrando no app do banco e digitando todas essas informações, porém, queria ver de facilitar e gerar um QR Code.

Mas realmente não encontrei isso na documentação do BACEN

**Comment by Robson-Rocha** [comment]
@FelipeZini, nesse caso muito provavelmente o que o banco está fazendo é buscando pelo CPF/CNPJ dos dados como chave. Sem a geração de uma chave, mesmo que aleatória, não há como fazer a transferência (pelo menos de acordo com a documentação).
