### ISSUE TITLE
[Dúvida] Recebimento em USD suportado?

### ISSUE THREAD

**Issue by bootsector** [fbbergamo/gerador-pix#6]
Olá!

Não necessariamente uma issue, mas uma dúvida: a especificação do PIX teoricamente suporta outras moedas através do campo "Transaction Currency".

O que acontece se for informado o ISO code "840" nesse campo pra uma conta PIX do Brasil? Funciona? Se sim, a conversão pra BRL é automática?

Obrigado pela excelente referência de implementação do PIX qr code!

**Comment by fbbergamo** [comment]
olá @bootsector acredito q o sistema pix e os bancos não vão processar. 

vc pode perguntar no forum do bacen, vão te responder melhor lá https://github.com/bacen/pix-perguntas-e-respostas/issues
