### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ruanpablodev** [fbbergamo/gerador-pix#8]
Ola, estou a muito tempo a procura de uma api que gera chave pix nesse estilo , teria como voce fazer uma?

**Comment by fbbergamo** [comment]
Olá, o site tem API. Só que tive que bloquear pq tava tendo muito robo, e não consigo manter uma infra para isso 

mas se vc conseguir subir o projeto deve funcionar algo assim 

```
curl 'http://localhost:8000/emvqr-static' \
          -H 'Content-Type: application/json;charset=UTF-8' \
          --data-binary '{"key_type":"Telefone","key":"9117bedf-de7d-4a4d-b55b-fc9ff06a8067","name":"FELIPE BARRETO BERGAMO","city":"São Paulo","amount":"R$ 5,00","reference":"CAFE Felipe"}'
      ```
