### ISSUE TITLE
Sugestão: Criar uma lib npm da class BRCode

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [fbbergamo/gerador-pix#9]
Seria possível externalizar a class BRCode e gerar uma lib npm dela? Pois estou com umas idéias de geração de qrcode pix, e sua lib seria sensacional ter como dependência, principalmente se for possível usá-la tanto no backend node como no frontend javascript puro.

**Comment by fbbergamo** [comment]
Olá, Se vc puder abrir um projeto separado mais p frente consigo migrar para a sua lib npm, eu realmente não tenho tempo esse ano para manter um pacote npm, mas se vc quiser puxar consigo ir ajudando com alguns PRs, tests, benchmark. 

Eu acho que deve funcionar o código no frontend, eu nunca testei, só fico em duvida na parte do código que é gerado os digitos verificadores se essas dependencias funcionam no navegador, mas devem funcionar, não teste ainda. 

Abraços,
